<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Simulation\Simulation.fsproj" />
    <ProjectReference Include="..\RealSim.Scenarios\RealSim.Scenarios.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\Simulation\Program.fs" Link="Program.fs" />
  </ItemGroup>

</Project>
